### ISSUE TITLE
Hint: Compile keyboard layout

### ISSUE THREAD

**Issue by erikarvstedt** [Infinisil/system#1]
I've edited the [Keyboard Layout Wiki entry](https://nixos.wiki/index.php?title=Keyboard_Layout_Customization) to use compiled keyboard layouts. This helps catching errors at build-time and improves startup performance.
Maybe you'd want to use this in [your config](
https://github.com/Infinisil/system/blob/41227b4addf48e7c99e7bed9ed95a547a603bd67/config/new-modules/keylayout.nix#L53).

**Comment by infinisil** [comment]
Nice! Might do that later

**Comment by infinisil** [comment]
Not relevant anymore, switched to a more standard keyboard layout configuration
