### ISSUE TITLE
Double "exa" in console config

### ISSUE THREAD

**Issue by TheSirC** [Infinisil/system#2]
I am using the fact that you have added `exa` twice (once [here](https://github.com/Infinisil/system/blob/c45ff6bb0e0df3c42f80a47383165055bdf09963/config/new-modules/console.nix#L53) and then [here](https://github.com/Infinisil/system/blob/c45ff6bb0e0df3c42f80a47383165055bdf09963/config/new-modules/console.nix#L57)) as a pretext to **thank you very much** for this example of configuration of yours I am using as a template for my own (once I figure out how to deploy to myself using `nixops`... :eyes:) : your work is appreciated.

I wish to have one day the same level of proficiency with Nix(OS) as you down the line.

Close the issue whenever, this is not important

**Comment by infinisil** [comment]
Hehe thanks, glad you can get something out of it :smiley:
